### ISSUE TITLE
Document contracts using NatSpec 

### ISSUE THREAD

**Issue by horky2004** [morganjweaver/08-Tokenized-Votes#14]
It is recommended that Solidity contracts are fully annotated using [NatSpec](https://docs.soliditylang.org/en/latest/natspec-format.html#natspec) for all public interfaces (everything in the ABI). I our case that means annotating pretty much everything. After this is implemented, when making changes to contracts we must always take care to update comments/documentation if necessary.

**Comment by morganjweaver** [comment]
Will do!
