### ISSUE TITLE
CustomBallot contract event declaration order

### ISSUE THREAD

**Issue by horky2004** [morganjweaver/08-Tokenized-Votes#16]
[Solidity coding guide](https://docs.soliditylang.org/en/latest/style-guide.html#order-of-layout) states the following order within the contract:

1. Type declarations
2. State variables
3. Events
4. Modifiers
5. Functions

Our CustomBallot.sol contract starts with event declaration and then moves on to a type declaration. Although I do see a lot of contracts on github that start with declaring events first. Following this guide, we should move event Voted under the last state variable. Opinions?

**Comment by morganjweaver** [comment]
Let's do it.

**Comment by morganjweaver** [comment]
Finished, is not open PR
